language: python
python:
 - "3.6"
cache: packages
install:
- pip install -U .
script:
- python -m pytest pooledparents/test_*.py
after_script:
- coverage run -m pytest pooledparents/test_*.py
- bash <(curl -s https://codecov.io/bash) -s .
